import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Nav  from '@/components/nav'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
     
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen">
            <div className="sticky top-0 z-10 bg-background">
              <Nav />
            </div>
            <main className="flex-grow overflow-y-auto">
              {children}
            </main>
            <footer className="w-full sticky bottom-0 bg-background bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 h-[7vh] flex items-center text-center justify-center">
              Smart Agent
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}